export const QuestionArray = (name) => {
  return [
    {
      question: `When was the last time you had a conversation with ${name}`,
      image: "./used/converse.png",
      q_no: 1,
      opt1: ["Recently", true],
      opt2: ["Its been weeks", false],
    },
    {
      question: `Have you and ${name} hanged out this month`,
      image: "./used/hang.png",
      q_no: 2,
      opt1: ["Nope been busy", false],
      opt2: ["Yes", true],
    },
    {
      question: `Have you ever defended ${name} character in their absensce`,
      image: "./used/defend.png",
      q_no: 3,
      opt1: ["All the time", true],
      opt2: ["I do sometimes", false],
    },
    {
      question: `Do you see funny memes and then think back to moments with ${name}`,
      image: "./used/memes.png",
      q_no: 4,
      opt1: ["I do often", true],
      opt2: ["Sometimes", false],
    },
    {
      question: `Do you feel comfortable talking with ${name} whenever you're down`,
      image: "./used/converse.png",
      q_no: 5,
      opt1: ["I prefer not", false],
      opt2: ["I do to feel better", true],
    },
    {
      question: `Have you shared an embarrasing moment with ${name}`,
      image: "./used/embarass.png",
      q_no: 6,
      opt1: ["a lot", true],
      opt2: ["Nah not really", false],
    },
    {
      question: `Do you feel the need to impress around ${name}`,
      image: "./used/oppress.png",
      q_no: 7,
      opt1: ["Sometimes", false],
      opt2: ["Not at all", true],
    },
    {
      question: `Have you seen ${name} very sad`,
      image: "./used/sad.png",
      q_no: 8,
      opt1: ["Yes i have", true],
      opt2: ["No not really", false],
    },
    {
      question: `How often do you and ${name} meet up`,
      image: "./used/hang.png",
      q_no: 9,
      opt1: ["couple times", false],
      opt2: ["Whenever we want", true],
    },
    {
      question: `Have you seen ${name} excited`,
      image: "./used/excited.png",
      q_no: 10,
      opt1: ["yess!!", true],
      opt2: ["Mayby", false],
    },
    {
      question: `Have you gotten drunk with ${name}`,
      image: "./used/drunk.png",
      q_no: 11,
      opt1: ["Yes i have", true],
      opt2: ["Not at all", false],
    },
    {
      question: `Would you describe ${name} as a close friend`,
      image: "./used/friend.png",
      q_no: 12,
      opt1: ["A little bit", false],
      opt2: ["Yes", true],
    },
    {
      question: `Would You share Your score with ${name} after this challenge`,
      image: "./used/custom.png",
      q_no: 13,
      opt1: ["I'll hide it", false],
      opt2: ["Yes nothing to hide", true],
    },
    {
      question: `Do you share ${name} funny memes constantly`,
      image: "./used/memes.png",
      q_no: 14,
      opt1: ["No we don't", false],
      opt2: ["All the time!", true],
    },
    {
      question: `Do you feel oppressed or try to impress when around ${name}`,
      image: "./used/oppress.png",
      q_no: 15,
      opt1: ["We dont care", true],
      opt2: ["Sometimes", false],
    },
  ];
};
